import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Download, FileCode } from "lucide-react";
import { toast } from "sonner";

export const CodePreview = () => {
  const [activeFile, setActiveFile] = useState("App.tsx");
  
  const sampleCode = `import React from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';

export default function App() {
  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-4xl mx-auto">
        <Card className="p-6">
          <h1 className="text-3xl font-bold mb-4">
            Welcome to Your Generated UI
          </h1>
          <p className="text-muted-foreground mb-6">
            This is a sample component generated by Inkwell AI.
            Your actual code will appear here once you generate.
          </p>
          <Button className="btn-generate">
            Get Started
          </Button>
        </Card>
      </div>
    </div>
  );
}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sampleCode);
    toast("Code copied to clipboard!");
  };

  const handleDownload = () => {
    const blob = new Blob([sampleCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = activeFile;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast("Code downloaded!");
  };

  return (
    <div className="panel h-full flex flex-col">
      <div className="panel-header flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileCode className="w-4 h-4" />
          <span>{activeFile}</span>
        </div>
        <div className="flex gap-1">
          <Button onClick={handleCopy} variant="ghost" size="sm" className="h-7 px-2">
            <Copy className="w-3 h-3" />
          </Button>
          <Button onClick={handleDownload} variant="ghost" size="sm" className="h-7 px-2">
            <Download className="w-3 h-3" />
          </Button>
        </div>
      </div>
      
      <div className="flex-1 overflow-hidden">
        <pre className="code-editor h-full overflow-auto p-4 text-sm leading-relaxed">
          <code className="text-foreground">{sampleCode}</code>
        </pre>
      </div>
    </div>
  );
};